// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9MKQaVT6mWBAoO73z5EN-c8rW7VBl18c',
    appId: '1:468514665975:web:29cb433e8d449aa669eaf2',
    messagingSenderId: '468514665975',
    projectId: 'b-todo-27c32',
    authDomain: 'b-todo-27c32.firebaseapp.com',
    storageBucket: 'b-todo-27c32.firebasestorage.app',
    measurementId: 'G-RG757Y5WPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfE84FJzPAebPMQ78uZaL4cWufeEBcqgw',
    appId: '1:468514665975:android:b6b9b235966cdcaf69eaf2',
    messagingSenderId: '468514665975',
    projectId: 'b-todo-27c32',
    storageBucket: 'b-todo-27c32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_9GSkuWLTHn_6a5f2D-au5UT7l4ja178',
    appId: '1:468514665975:ios:10f5b386723f78e469eaf2',
    messagingSenderId: '468514665975',
    projectId: 'b-todo-27c32',
    storageBucket: 'b-todo-27c32.firebasestorage.app',
    androidClientId: '468514665975-2jkiigjqg4srdvb5ltcmgp14jn40116u.apps.googleusercontent.com',
    iosClientId: '468514665975-ckh8mt5lrk47kgi336mqi70l6ccjju4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_9GSkuWLTHn_6a5f2D-au5UT7l4ja178',
    appId: '1:468514665975:ios:10f5b386723f78e469eaf2',
    messagingSenderId: '468514665975',
    projectId: 'b-todo-27c32',
    storageBucket: 'b-todo-27c32.firebasestorage.app',
    androidClientId: '468514665975-2jkiigjqg4srdvb5ltcmgp14jn40116u.apps.googleusercontent.com',
    iosClientId: '468514665975-ckh8mt5lrk47kgi336mqi70l6ccjju4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9MKQaVT6mWBAoO73z5EN-c8rW7VBl18c',
    appId: '1:468514665975:web:addb49d1b6e5df4b69eaf2',
    messagingSenderId: '468514665975',
    projectId: 'b-todo-27c32',
    authDomain: 'b-todo-27c32.firebaseapp.com',
    storageBucket: 'b-todo-27c32.firebasestorage.app',
    measurementId: 'G-BM9H9CH45R',
  );

}